  const ipcModules = [
    "./ipc/utils/updater/index.ipc.js",
    "./ipc/core/player/index.ipc.js",
    "./ipc/core/notification/index.ipc.js",
    "./ipc/core/settings/index.ipc.js",
    "./ipc/core/twitch-auth/index.ipc.js",
    "./ipc/core/twitch-chat/index.ipc.js",
    "./ipc/core/follows/index.ipc.js",
    "./ipc/core/games/index.ipc.js",
    "./ipc/core/user/index.ipc.js",
    "./ipc/core/clips/index.ipc.js",
    "./ipc/core/eventsub/index.ipc.js",
    "./ipc/core/history/index.ipc.js",
    "./ipc/core/shortcut/index.ipc.js",
    "./ipc/core/themes/index.ipc.js",
    "./ipc/core/ad-block/index.ipc.js",
    "./ipc/core/pip/index.ipc.js",
    "./ipc/core/download/index.ipc.js",
    "./ipc/core/predictions/index.ipc.js",
    "./ipc/core/search/index.ipc.js",
    "./ipc/core/streams/index.ipc.js",
    "./ipc/core/whisper/index.ipc.js",
    "./ipc/core/notification-store/index.ipc.js",
    "./ipc/core/stream-settings/index.ipc.js",
    "./ipc/core/stream-manager/index.ipc.js",
    "./ipc/core/analytics/index.ipc.js",
    "./ipc/core/chat-history/index.ipc.js",
    "./ipc/core/moderation-log/index.ipc.js",
    "./ipc/core/scheduler/index.ipc.js",
    "./ipc/core/chat-commands/index.ipc.js",
    "./ipc/core/pinned-messages/index.ipc.js",
  ];

module.exports = {ipcModules};