// src/main/services/settings/defaults.js

const defaults = {
  theme: "dark",
  language: "en",
  notificationsEnabled: true,
  notificationPreferences: {
    stream_live: true,
    new_follower: true,
    subscription: true,
    gift_sub: true,
    raid: true,
    hype_train: true,
  },
  autoPlay: true,
  chatFilters: [],
  accounts: {},
  twitch: {},
  activeAccountId: null,
  automationConfig: {
    autoRaid: false,
    autoClip: false,
    autoMessage: false,
    autoMessageText: "Thanks for the follow/sub! 🎉",
    raidTarget: null,
    autoSlowMode: false,
    slowModeSpamThreshold: 5,
    slowModeWaitTime: 10,
    slowModeDuration: 60,
    autoFollowerMode: false,
    followerModeDuration: 5,
    autoShoutoutOnRaid: false,
    shoutoutMessage: "Thanks for the raid @{fromBroadcasterName}! Check them out at twitch.tv/{fromBroadcasterName}",
    autoClipOnChatSpike: false,
    chatSpikeThreshold: 100,
    chatSpikeCooldownMinutes: 5,
    autoStreamMarkers: false,
    markerIntervalMinutes: 30,
    autoModerationEnabled: false,
    autoBlockLinks: false,
    blockedTerms: [],
    blockedBadges: [],
    autoDeleteMessage: false,
    autoTimeoutUser: true,
    repeatWindowSeconds: 10,
    repeatCountThreshold: 3,
  },
};

module.exports = { defaults };